apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.configName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  LAYER_GATEWAY_URL: {{ .Values.layer.gatewayUrl | quote }}
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
